apiVersion: "sparkoperator.k8s.io/v1beta1"
kind: SparkApplication
metadata:
  name: spark-word
  namespace: spark-jobs
spec:
  type: Java
  mode: cluster
  image: "gcr.io/spark-operator/spark:v2.4.0"
  imagePullPolicy: Always
  mainClass: com.test.sprak.k8.sample.MyWordCounter
  mainApplicationFile: "hdfs://192.168.100.113:9000/usr/local/hadoop/jars/SparkTestApp-1.0.jar"
  sparkVersion: "2.4.0"
  restartPolicy:
    type: Never
  volumes:
    - name: "test-volume"
      hostPath:
        path: "/tmp"
        type: Directory
  driver:
    cores: 0.1
    coreLimit: "200m"
    memory: "512m"
    labels:
      version: 2.4.0
    serviceAccount: spark
    volumeMounts:
      - name: "test-volume"
        mountPath: "/tmp"
   executor:
      cores: 1
      instances: 1
      memory: "512m"
      labels:
        version: 2.4.0
      volumeMounts:
        - name: "test-volume"
          mountPath: "/tmp"